### ISSUE TITLE
puzzle 3 code is wrong

### ISSUE THREAD

**Issue by vitheshshetty00** [hganchev/Python_FestoCodingChallenge2022#1]
in puzzle 3 solution,only for 7 o clock minutes should be less than 14,for all time less than 7 o clock minutes can be anything.

**Comment by hganchev** [comment]
ah, yea! Thanks, I was wondering where am I wrong :)

**Comment by hganchev** [comment]
https://github.com/hganchev/Python_FestoCodingChallenge2022/commit/11c1e1291ed27d575c293021f0ca114513e53b9e

This should be the case :)
